# Generated by Django 2.2.6 on 2021-01-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anwar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
